### ISSUE TITLE
Issue setting bot up, I'm sure it's something I did incorrectly (at least I'm honest)

### ISSUE THREAD

**Issue by CthulhuCrisis** [Malexion/Rhythm-Bot#37]
Just got everything installed and set up, !search function works, but as soon as I select a song to play with the Like Emote, I get this:

C:\Windows\system32>npm start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Windows\system32\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Windows\system32\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Plexbox\AppData\Roaming\npm-cache\_logs\2021-02-28T01_12_11_516Z-debug.log

C:\Windows\system32>cd C:\Users\Plexbox\Documents\Rhythm-Bot-master

C:\Users\Plexbox\Documents\Rhythm-Bot-master>npm start

> rhythm-bot@2.1.5 start C:\Users\Plexbox\Documents\Rhythm-Bot-master
> tsc && node dist/app

[2021-02-28T01:12:35.206Z] (debug): Rhythm Bot Online
[2021-02-28T01:12:35.217Z] (debug): Bot Online
Guilds: 1
Guild Name: Cthulhu Crisis
- Can Manage Messages: false
[2021-02-28T01:12:55.288Z] (debug): Bot Command: !search fratellis costello music
[2021-02-28T01:12:59.750Z] (debug): Emoji Click: Adding Media: https://youtube.com/watch?v=0gpMlAiqcjU
C:\Users\Plexbox\Documents\Rhythm-Bot-master\node_modules\discord-bot-quickstart\lib\models\bot.model.js:10
process.on('unhandledRejection', error => this.log.error('Uncaught Promise Rejection', error));
                                                   ^

TypeError: Cannot read property 'error' of undefined
    at process.<anonymous> (C:\Users\Plexbox\Documents\Rhythm-Bot-master\node_modules\discord-bot-quickstart\lib\models\bot.model.js:10:52)
    at process.emit (events.js:315:20)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rhythm-bot@2.1.5 start: `tsc && node dist/app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rhythm-bot@2.1.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Plexbox\AppData\Roaming\npm-cache\_logs\2021-02-28T01_12_59_897Z-debug.log

**Comment by CthulhuCrisis** [comment]
[2021-02-28T01_12_59_897Z-debug.log](https://github.com/Malexion/Rhythm-Bot/files/6056114/2021-02-28T01_12_59_897Z-debug.log)

**Comment by CthulhuCrisis** [comment]
UPDATE: I ran "npm init" and it fixed the package.json error, but now I receive this:

C:\Users\Plexbox\Documents\Rhythm-Bot-master>npm start

> rhythm-bot@2.1.5 start C:\Users\Plexbox\Documents\Rhythm-Bot-master
> tsc && node dist/app

[2021-02-28T01:46:22.176Z] (debug): Rhythm Bot Online
[2021-02-28T01:46:22.187Z] (debug): Bot Online
Guilds: 1
Guild Name: Cthulhu Crisis
- Can Manage Messages: false
[2021-02-28T01:47:38.363Z] (debug): Bot Command: !search Fallout boy
[2021-02-28T01:47:43.619Z] (debug): Emoji Click: Adding Media: https://youtube.com/watch?v=C6MOKXm8x50
C:\Users\Plexbox\Documents\Rhythm-Bot-master\node_modules\discord-bot-quickstart\lib\models\bot.model.js:10
process.on('unhandledRejection', error => this.log.error('Uncaught Promise Rejection', error));
                                                   ^

TypeError: Cannot read property 'error' of undefined
    at process.<anonymous> (C:\Users\Plexbox\Documents\Rhythm-Bot-master\node_modules\discord-bot-quickstart\lib\models\bot.model.js:10:52)
    at process.emit (events.js:315:20)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rhythm-bot@2.1.5 start: `tsc && node dist/app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rhythm-bot@2.1.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Plexbox\AppData\Roaming\npm-cache\_logs\2021-02-28T01_47_43_740Z-debug.log

**Comment by TheOnlyBrian** [comment]
Change the package.json's start command from `tsc && node dist/app` to `tsc; node dist/app`. 


This link isn't a solution to your environment, it's a knowledge article on your problem. https://superuser.com/questions/464109/replacements-for-ampersand-and-double-ampersand-in-powershell
