### ISSUE TITLE
Issue starting code

### ISSUE THREAD

**Issue by Billowy-Waffle** [Malexion/Rhythm-Bot#66]
When I enter "npm start" in my cmd it says:
For help, see: https://nodejs.org/en/docs/inspector
Uncaught Promise Rejection Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (C:\Users\hudso\Desktop\Rhythm-Bot-master\node_modules\discord.js\src\client\Client.js:206:52)
    at RhythmBot.connect (C:\Users\hudso\Desktop\Rhythm-Bot-master\node_modules\discord-bot-quickstart\lib\models\bot.model.js:77:28)
    at C:\Users\hudso\Desktop\Rhythm-Bot-master\src\app.ts:31:13
    at Generator.next (<anonymous>)
    at C:\Users\hudso\Desktop\Rhythm-Bot-master\src\app.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\hudso\Desktop\Rhythm-Bot-master\src\app.ts:4:12)
    at C:\Users\hudso\Desktop\Rhythm-Bot-master\src\app.ts:9:13
    at Object.<anonymous> (C:\Users\hudso\Desktop\Rhythm-Bot-master\src\app.ts:38:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  [Symbol(code)]: 'TOKEN_INVALID'

The discord bot token is not wrong. I've tried multiple times with different regenerated tokens in the bot-config json file. I'm very new to this stuff so I may just be making a trivial mistake.

**Comment by chloeeee210** [comment]
Hello, I'm foreigner from another country.
How did you get it? I'cannot find answer.. I'm stucked in same problem.
please answer if you solved this.
