### ISSUE TITLE
eror with sodium modules

### ISSUE THREAD

**Issue by pengengantibaju** [Malexion/Rhythm-Bot#79]
root@1710541285woiden:~/bot# npm install

> sodium@3.0.2 preinstall /root/bot/node_modules/sodium
> node install.js --preinstall

Static libsodium was not found at /root/bot/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
libtool is required, but wasn't found on this system
make: *** [Makefile:62: libsodium] Error 1
/root/bot/node_modules/sodium/install.js:293
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/root/bot/node_modules/sodium/install.js:293:19)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@3.0.2 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@3.0.2 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-14T06_44_47_676Z-debug.log

**Comment by luiscmartinez** [comment]
Interesting, I am getting this too 
Have you made any progress? @pengengantibaju

**Comment by luiscmartinez** [comment]
Fixed it.
All you gotta do it follow the install directions here [sodium](https://www.npmjs.com/package/sodium)

**Comment by luiscmartinez** [comment]
1. brew install libtool autoconf automake
2. npm install node-gyp -g
